server:
  port: 9401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
#        默认端口8719,加入被占用会自动从8719开始依次+1扫描,直到找到未被占用的端口
        port: 8719
#        配置sentinel dashboard地址
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'

