spring:
  profiles:
    active: test


---
spring:
  redis:
    password: 619619Tey
    cluster:
      max-redirects: 3
      nodes:
      - 120.26.173.145:7001
      - 120.26.173.145:7002
      - 120.26.173.145:7003
      - 120.26.173.145:7004
      - 124.71.160.44:7001
      - 124.71.160.44:7002
    timeout: 10000ms
#    jedis:
#          pool:
#            max-active: 8
#            max-wait: -1ms
#            time-between-eviction-runs: 1000ms
  session:
    store-type: redis
  profiles: dev

server:
  port: 8001
