server:
  port: 9527
spring:
  application:
    name: cloud-gateway01
  cloud:
    gateway:
      routes:
        - id: atguigu-consumer #路由id,没有固定的规则,但是要求唯一,建议配合服务名
#          uri:  http://localhost:4000 #匹配后提供服务的路由地址
          uri:  lb://atguigu-consumer #配合discovery.locator.enabled=true使用 可做服务负载
          predicates: #断言:路径相匹配的进行路由
            - Path=/atguigu-consumer/**
        - id: atguigu-provider
          uri:  lb://atguigu-provider
          predicates:
            - Path=/atguigu-provider/**
      discovery:
        locator:
          enabled: true
  redis:
    port: 6379
    host: 120.26.173.145
eureka:
  instance:
    hostname: cloud-gateway02
    instance-id: cloud-gateway03
  client:
    service-url:
      defaultZone: http://eurekaserver5000.com:5000/eureka
#jwt生成密钥
jwt:
  secret:
    key: asdfghjkl
#token黑名单 存储key
  blacklist:
    key:
      format: JWT_BLACKLIST::%s
auth:
  skip:
    urls: /aiplatformauth/auth,/aiplatformauth/token/refresh