server:
  port: 9101
spring:
  profiles:
    active: dev
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

#\u6D88\u8D39\u8005\u5C06\u8981\u8BBF\u95EE\u7684\u5FAE\u670D\u52A1\u540D\u79F0,\u4E3A\u4E86\u65B9\u4FBF\u5199\u6240\u4EE5\u81EA\u5B9A\u4E49\u4E86\u4E00\u4E2A\u524D\u7F00
service-url:
  nacos-user-service: http://nacos-payment-provider
