server:
  port: 9011
  #tomcat:
  #  max-connections: 180000
  #  max-swallow-size: -1
  #  max-http-form-post-size: -1
  #ssl:
    #key-store: XXXXXX.pfx #政府提供真证书
    #key-alias: alias
    #key-store-password: XXXXXXXX #密钥8位
    #key-store-type: PKCS12
    #enabled: true

spring:
  application:
    name: aiplatform-auth
  redis:
    host: 192.168.0.115
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-wait: 10000ms
        max-idle: 8
        min-idle: 5
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/smartagriculture?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
    pg:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/smartagriculture
      username: postgres
      password: postgres
      type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.115:8848

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  #mvc:
  #  static-path-pattern: /static/**

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
  #实例默认通过使用域名形式注册到注册中心:false
    prefer-ip-address: true
  #实例名
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
mybatis:
  mapper-locations: classpath*:/mybatis/**/*.xml
  type-aliases-package: com.smart.aiplatformauth.model
  configuration:
    map-underscore-to-camel-case: false  #开启驼峰命名方式
    cache-enabled: true               #全局映射器启用缓存
    lazy-loading-enabled: true    #查询时，关闭关联对象即时加载以提高性能
    aggressive-lazy-loading: false   #设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指定)，不会加载关联表的所有字段，以提高性能
    multiple-result-sets-enabled: true  #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
logging:
  level:
    com:
      smart:
        aiplatformauth:
          mapper: debug
#druid:
#  url: jdbc:mysql://127.0.0.1:3306/smartagriculture?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
#  driver-class: com.mysql.cj.jdbc.Driver
#  username: root
#  password: root
#  initial-size: 1
#  min-idle: 1
#  max-active: 20
#  test-while-idle: true
#  test-on-borrow: false
#  test-on-return: false
#  max-wait: 60000
#  validation-query: select 'x' from dual
#  filters: stat,wall
#  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000

#jwt生成密钥
jwt:
  secret:
    key: asdfghjkl
#refreshToken 存储key
  refresh:
    token:
      key:
        format: JWT_REFRESH_TOKEN::%s
#token黑名单 存储key
  blacklist:
    key:
      format: JWT_BLACKLIST::%s
#refreshToken过期时间：60min
refresh:
  token:
    expire:
      time: 3600000
#token过期时间：30min,刷新后的token过期时间是当前的2倍
token:
  expire:
    time: 1800000

#配置分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#页面的地址
Instructions:
  path: https://www.baidu.com/
  image: /static/
  imagepathurl: image/
  imagepath: C:\\image\\
  #imagepath: /home/image/

wx:
  miniapp:
    #    appid: wx8038661dab5c3f73
    #    secret: 06623063c8b63bd947ffacb6dcadd0ec
    appid: wxd582b9fab97b638d
    secret: 1351e8315ea5d5bde44ae72e58c7f4cc
    msgDataFormat: JSON