server:
  port: 4000
  servlet:
    context-path: /atguigu-consumer
spring:
  application:
    name: atguigu-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间,1则表示全部采集
    probability: 1
eureka:
  instance:
    instance-id: consumer4000
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver5000.com:5000/eureka/,http://eurekaserver5001.com:5001/eureka
feign:
  hystrix:
    enabled: true
#ribbon超时时间设置
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 80000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 80000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

#hystrix超时时间设置
hystrix:
  command:
   #default全局有效，service id指定应用有效
    default:
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
logging:
  level:
    com.atguigu.spring.cloud.service: debug